package at.tuwien.prip.model.project.selection;

public enum SelectionType {

	TABLE, TABLE_REGION, TABLE_CELL, TABLE_COLUMN, TABLE_ROW, TABLE_ACCESSOR_CELL,
	LIST, LIST_ITEM, 
	PARAGRAPH, TEXTLINE, TEXT, FIGURE, 
	SECTION, CONCEPT_SECTION,
	HEADING, FOOTER, HEADER, SEMANTIC,
	FUNCTIONAL, FUN_TOC, FUN_ADVERTISMENT, FUN_NAVIGATION, 
	EXTRACTION, EXAMPLE, 
	NODE, SEGMENT, REGION, LABEL,
	PDF, PDF_INSTRUCTION, DOCUMENT, IMAGE, CAPTION
}
