

/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is mozdom4java
 *
 * The Initial Developer of the Original Code is
 * Peter Szinek, Lixto Software GmbH, http://www.lixto.com.
 * Portions created by the Initial Developer are Copyright (C) 2005-2006
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *  Peter Szinek (peter@rubyrailways.com)
 *  Michal Ceresna (michal.ceresna@gmail.com)
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */


package org.mozilla.dom.events;

//Java imports
import java.util.concurrent.Callable;

import org.mozilla.dom.ThreadProxy;
import org.mozilla.dom.views.AbstractViewImpl;
import org.mozilla.interfaces.nsIDOMAbstractView;
import org.mozilla.interfaces.nsIDOMKeyEvent;
import org.w3c.dom.views.AbstractView;



public class KeyEventImpl extends UIEventImpl //implements org.w3c.dom.events.KeyEvent
{


    public nsIDOMKeyEvent getInstance()
    {
	return getInstanceAsnsIDOMKeyEvent();
    }

    /***************************************************************
     *
     * KeyEvent implementation code
     *
     ***************************************************************/

    public KeyEventImpl(nsIDOMKeyEvent mozInst)
    {
        super( mozInst );
    }

    public static KeyEventImpl getDOMInstance(nsIDOMKeyEvent mozInst)
    {
        
        KeyEventImpl node = (KeyEventImpl) instances.get(mozInst);
        return node == null ? new KeyEventImpl(mozInst) : node;
    }

    public nsIDOMKeyEvent getInstanceAsnsIDOMKeyEvent()
    {
        if (moz==null)
            return null;
        else
            return (nsIDOMKeyEvent) moz.queryInterface(nsIDOMKeyEvent.NS_IDOMKEYEVENT_IID);
    }

    public long getCharCode()
    {
        //METHOD-BODY-START - autogenerated code
        Callable<Long> c = new Callable<Long>() { public Long call() {
            long result = getInstanceAsnsIDOMKeyEvent().getCharCode();
            return result;
        }};
        return ThreadProxy.getSingleton().syncExec(c);
        //METHOD-BODY-END - autogenerated code
    }

    public boolean getMetaKey()
    {
        //METHOD-BODY-START - autogenerated code
        Callable<Boolean> c = new Callable<Boolean>() { public Boolean call() {
            boolean result = getInstanceAsnsIDOMKeyEvent().getMetaKey();
            return result;
        }};
        return ThreadProxy.getSingleton().syncExec(c);
        //METHOD-BODY-END - autogenerated code
    }

    public boolean getCtrlKey()
    {
        //METHOD-BODY-START - autogenerated code
        Callable<Boolean> c = new Callable<Boolean>() { public Boolean call() {
            boolean result = getInstanceAsnsIDOMKeyEvent().getCtrlKey();
            return result;
        }};
        return ThreadProxy.getSingleton().syncExec(c);
        //METHOD-BODY-END - autogenerated code
    }

    public boolean getShiftKey()
    {
        //METHOD-BODY-START - autogenerated code
        Callable<Boolean> c = new Callable<Boolean>() { public Boolean call() {
            boolean result = getInstanceAsnsIDOMKeyEvent().getShiftKey();
            return result;
        }};
        return ThreadProxy.getSingleton().syncExec(c);
        //METHOD-BODY-END - autogenerated code
    }

    public boolean getAltKey()
    {
        //METHOD-BODY-START - autogenerated code
        Callable<Boolean> c = new Callable<Boolean>() { public Boolean call() {
            boolean result = getInstanceAsnsIDOMKeyEvent().getAltKey();
            return result;
        }};
        return ThreadProxy.getSingleton().syncExec(c);
        //METHOD-BODY-END - autogenerated code
    }

    public long getKeyCode()
    {
        //METHOD-BODY-START - autogenerated code
        Callable<Long> c = new Callable<Long>() { public Long call() {
            long result = getInstanceAsnsIDOMKeyEvent().getKeyCode();
            return result;
        }};
        return ThreadProxy.getSingleton().syncExec(c);
        //METHOD-BODY-END - autogenerated code
    }

    public void initKeyEvent(final String arg1, final boolean arg2, final boolean arg3, final AbstractView arg4, final boolean arg5, final boolean arg6, final boolean arg7, final boolean arg8, final long arg9, final long arg10)
    {
        //METHOD-BODY-START - autogenerated code
        final nsIDOMAbstractView mozArg4 = arg4!=null ? ((AbstractViewImpl) arg4).getInstance() : null;
        final Runnable r = new Runnable() { public void run() {
            getInstanceAsnsIDOMKeyEvent().initKeyEvent(arg1, arg2, arg3, mozArg4, arg5, arg6, arg7, arg8, arg9, arg10);
        }};
        ThreadProxy.getSingleton().syncExec(r);
        //METHOD-BODY-END - autogenerated code
    }



}
